### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by gandalf34** [Gru80/obsidian-regex-replace#17]
doesn't show up in command palette. Cant assign hotkey. I am on latest v 16.5 and installer 15.9 . Win 11 tried uninstall of plugin tired solo on empty vault with no other plugin. Uninstalled reinstalled obsidian . Nothing

I can provide more info / data .

**Comment by willasm** [comment]
Same under windows 10 with v0.15.9, however I can assign a hot key but nothing happens when it's entered. Does not show up in the command palette at all for me as well. Hope this can be fixed as I would get a lot of use from this.

**Comment by Gru80** [comment]
Hi, thanks for your reports.
Can you please check if the problem still occurs if you update to the latest version of Obsidian? (V1.0 was released just a few days ago)

**!! IMPORTANT !!**
If you **uninstall** the plugin and **re-install** it - you still need to **_enable_** it in the "Community Plugins" Settings page. Otherwise it will not show up in the command palette (and also hotkeys will not work)


I have not been able to reproduce it, neither with 0.15.9 nor with 1.0 (unfortunately i have no access to insider builds, so I was not able to check it with 16.5)

**Comment by willasm** [comment]
Sorry for not getting back sooner but happy to report that it is working great in the new update! Have not tested it to extensively but so far it seems to work perfectly! Really useful plugin for me, thank you.

**Comment by gandalf34** [comment]
It started working once I uninstalled everything related to Obsidian (and even old vault's) and reinstalles. I guess something else was getting in the way

**Comment by Gru80** [comment]
thanks a lot for the feedback!
