### ISSUE TITLE
Feature Request: Use from regular find & replace dialog

### ISSUE THREAD

**Issue by alanalvarado** [Gru80/obsidian-regex-replace#8]
would it be possible to use it from the regular find & replace dialog?

**Comment by Gru80** [comment]
Actually, from the feature-point of view: since this plugin has some additional "native" options, it is not possible to use the regular find & replace dialog.

However, there is already another plugin which seems to do exactly what you are looking for: https://github.com/nothingislost/obsidian-regex-search-replace
